name: Main Branch Protection

on:
  pull_request:
    branches:
      - main

jobs:
  run_if:
    if: ${{ (github.head_ref == 'unstable') || startsWith(github.head_ref, 'hotfix/') }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Pull request on main must come from 'unstable' or from 'hotfix/**'"
